sudo: required
if: branch = master

services:
  - docker
  - mongodb

before_script:
  # Log in to the Docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin

  # Build test image
  - docker build -f dev.dockerfile -t hugovp/node-todo-api:test .

script: |
  ./wait-for.sh 127.0.0.1:27017 -- 
    docker run -it \
      -e PORT=5000 \
      -e MONGODB_URI=mongodb://127.0.0.1:27017/TodoAppTest \
      -e JWT_SECRET=123abc \
      --network host \
      -h 127.0.0.1 \
      hugovp/node-todo-api:test \
      npm run test

after_success:
  # Build production image
  - docker build -f dockerfile -t hugovp/node-todo-api .

deploy:
  - provider: script
    script:
      # Take the image and push it to Docker Hub
      docker push hugovp/node-todo-api

  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: $HEROKU_APP_NAME
