version: '3'
services:
  api:
    restart: on-failure
    build:
      dockerfile: dev.dockerfile
      context: ./
    ports:
      - 3000:3000
    volumes:
      - /app/.git
      - /app/node_modules
      - ./:/app
    environment: 
      MONGODB_URI: mongodb://db:27017/TodoApp
      JWT_SECRET: 123abc
      PORT: 3000

  db:
    restart: always
    image: mongo:latest
    ports: 
      - 10101:27017
    volumes:
      - $HOME/dbdata:/data/db
